// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiU2kKZe0IoTwNIm8AosnjNSALOLa-gYo',
    appId: '1:213587292557:web:628abe46931a9904574dc4',
    messagingSenderId: '213587292557',
    projectId: 'response-53907',
    authDomain: 'response-53907.firebaseapp.com',
    storageBucket: 'response-53907.appspot.com',
    measurementId: 'G-NLKRDP1C07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0-VD-am-H0GZV0lYh9AGZ6_s6Xd1zgk',
    appId: '1:213587292557:android:975fae2f31abf064574dc4',
    messagingSenderId: '213587292557',
    projectId: 'response-53907',
    storageBucket: 'response-53907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUFS9vFclPBmmVzkQRKqQhbWx29O9Zio',
    appId: '1:213587292557:ios:63b1183d5362894f574dc4',
    messagingSenderId: '213587292557',
    projectId: 'response-53907',
    storageBucket: 'response-53907.appspot.com',
    iosBundleId: 'com.example.response',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqUFS9vFclPBmmVzkQRKqQhbWx29O9Zio',
    appId: '1:213587292557:ios:f6f299435a1243ee574dc4',
    messagingSenderId: '213587292557',
    projectId: 'response-53907',
    storageBucket: 'response-53907.appspot.com',
    iosBundleId: 'com.example.response.RunnerTests',
  );
}
